embedder:
  {
    "layer": "penultimate",
    "pretrained": "../_runtime/models/stable-diffusion-v/open_clip_pytorch_model.bin",
  }

auto_encoder:
  {
    "ddconfig":
      {
        "double_z": True,
        "z_channels": 4,
        "resolution": 256,
        "in_channels": 3,
        "out_ch": 3,
        "ch": 128,
        "ch_mult": [1, 2, 4, 4],
        "num_res_blocks": 2,
        "attn_resolutions": [],
        "dropout": 0.0,
        "video_kernel_size": [3, 1, 1],
      },
    "embed_dim": 4,
    "pretrained": "../_runtime/models/v2-1_512-ema-pruned.ckpt",
  }

vid_dataset:
  {
    "type": "MotionVideoFeatureDataset",
    "gh_images_feature_dir": "../_demo_data/change_motion",
    "zero_y_path": "../_demo_data/zero_y.pt",
  }

UNet: {
    "in_dim": 4,
    "dim": 320,
    "y_dim": 1024,
    "context_dim": 1024,
    "out_dim": 4,
    "dim_mult": [1, 2, 4, 4],
    "num_heads": 8,
    "head_dim": 64,
    "num_res_blocks": 2,
    "attn_scales": [1.0, 0.5, 0.25],
    "dropout": 0.1,
    "temporal_attention": True,
    "temporal_attn_times": 1,
    "use_checkpoint": True,
    "use_fps_condition": False,
    "use_sim_mask": False,
    "use_lora": true,
    "lora_rank": 4,
    "lora_alpha", # In yaml, 'None' does not need to be specified.
  }

Diffusion:
  {
    "schedule": "linear_sd",
    "schedule_param":
      {
        "num_timesteps": 1000,
        "init_beta": 0.00085,
        "last_beta": 0.0120,
        "zero_terminal_snr": False,
      },
    "mean_type": "eps",
    "loss_type": "mse",
    "var_type": "fixed_small",
    "rescale_timesteps": False,
    "noise_strength": 0.,
  }

grad_scale: {
    "spatial": 1, # For LoRA, we do not specify the learning rate like ModelScope.
    "temporal": 1,
  }

infer_checkpoint: ../_runtime/non_ema_0640000.pth

concat_input: true
scale_factor: 0.18215

sample_fps: 8
max_frames: 16

batch_sizes: { "1": 16, "4": 8, "8": 4, "16": 1, "24": 1, "32": 1 }

guide_scale: 3.0
ddim_timesteps: 20
use_fp16: true

new_caption: "The scene features a man and a woman jumping in the same rhythm to celebrate together on a street at night. The man is wearing a tie, which suggests a formal or semi-formal attire. The woman is wearing a yellow dress, adding a pop of color to the scene. They are both dancing in the middle of the street, surrounded by a cityscape. The atmosphere is lively and energetic, with the couple enjoying their time together as they dance. The street is well-lit, with the man and woman being the main focus of the scene. The colors of the night sky and the streetlights create a warm and inviting ambiance. The man and woman appear to be having a great time, as they are both smiling and enjoying their dance. The setting is a city street at night, with the couple dancing in the middle of the road. The man and woman are the main characters in the scene, and their interaction and expressions convey a sense of joy and connection. The background features the cityscape, which adds depth and context to the scene."

save_dir: ../_demo_results/change_motion
